apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo Workflow
on:
  workflow_dispatch:
jobs:
  scan:
    steps:
      - name: Scan with Black Duck SCA
        uses: cloudbees-io/blackduck-sca-scan-dependency@v2
        with:
          server-url: ${{ vars.BLACK_DUCK_URL }}
          api-token: ${{ secrets.BLACK_DUCK_TOKEN }}
          ref: main
          project-name: "blackduck-demo"
          project-version: "1.0.0"
      - name: Report evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            # Scanner results
            Critical: ${{ steps.scan.outputs.critical-count }}
            Very High: ${{ steps.scan.outputs.very-high-count }}
            High: ${{ steps.scan.outputs.high-count }}
            Medium: ${{ steps.scan.outputs.medium-count }}
            Low: ${{ steps.scan.outputs.low-count }}
      - name: Security gate
        if: steps.scan.outputs.critical-count > 0 || steps.scan.outputs.very-high-count > 0
        uses: docker://alpine:3.20
        run: |
          echo "Security gate failed"
          exit 1
  build:
    needs:
      - scan
    steps:
      - name: Call workflow
        id: call-workflow
        with:
          token: ${{ secrets.GHA_TOKEN }}
          org-name: ldorg
          repo-name: blackduck-demo
          branch-name: main
          workflow-name: basic
        uses: cloudbees-io/ghactions-run-workflow@v2
