apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Call workflow
        id: call-workflow
        with:
          token: ${{ secrets.GHA_TOKEN }}
          org-name: ldorg
          repo-name: blackduck-demo
          branch-name: main
          workflow-name: basic
        uses: cloudbees-io/ghactions-run-workflow@v2
      - name: Report evidence
        uses: docker://alpine:1.20
        run: |
          echo << 'EOF'
            ${{ steps.call-workflow.output }}
          EOF
