name: scan
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Scan with Black Duck SCA
        uses: cloudbees-io-gha/black-duck-scan-publish@998deefed58a1f5ed7417d6ac42c8bf241f0a346
        with:
          api-token: ${{ secrets.BLACK_DUCK_TOKEN }}
          server-url: ${{ vars.BLACK_DUCK_URL }}
          project-name: "blackduck-demo"
          project-version: "1.0.0"
